######################################################
#              SimplyHub Config File                 #
######################################################
#set to true or false                                
compass_on_spawn: true                           
compass_enabled: true
torch_on_spawn: true
torch_enabled: true                        
allow_player_pop: true
clear_inv_on_spawn: true
compass_item_1_enabled: true
compass_item_2_enabled: true
compass_item_3_enabled: true
compass_item_4_enabled: true
compass_item_5_enabled: true
compass_item_6_enabled: true
compass_item_7_enabled: true
compass_item_8_enabled: true
compass_item_9_enabled: true
#######################################################
#Supports color codes
compass_name: '&6Teleportation'
compass_item_name_1: '&6Soon'
compass_item_name_2: '&bSoon'
compass_item_name_3: '&aSoon'
compass_item_name_4: '&3Soon'
compass_item_name_5: '&5Soon'
compass_item_name_6: '&8Soon'
compass_item_name_7: '&9Soon'
compass_item_name_8: '&1Soon'
compass_item_name_9: '&2Soon'
compass_item_lore_1: '&6Soon'
compass_item_lore_2: '&bSoon'
compass_item_lore_3: '&aSoon'
compass_item_lore_4: '&3Soon'
compass_item_lore_5: '&5Soon'
compass_item_lore_6: '&8Soon'
compass_item_lore_7: '&9Soon'
compass_item_lore_8: '&1Soon'
compass_item_lore_9: '&2Soon'
toggle_players_item_on_name: '&6Hide players'
toggle_players_item_off_name: '&6Show players'
toggle_players_item_on_lore: '&cRight click to use'
toggle_players_item_off_lore: '&cRight click to use'
#DO NOT ADD A / UNLESS THE COMMAND USES '//'.
compass_item_command_1: 'command1'
compass_item_command_2: 'command2'
compass_item_command_3: 'command3'
compass_item_command_4: 'command4'
compass_item_command_5: 'command5'
compass_item_command_6: 'command6'
compass_item_command_7: 'command7'
compass_item_command_8: 'command8'
compass_item_command_9: 'command9'
#########################################################
#Messages:
pop_player_message: '&4POP!'
hide_players_message: '&6You can no longer see players!'
show_players_message: '&6You can now see players!'
torch_on_cooldown_message: '&4You must wait to toggle players!'
no_perms_message: '&4You do not have permission to do that command!'
#If you do not want a message, put 'null'.
compass_item_message_1: '&1message1'
compass_item_message_2: '&3message2'
compass_item_message_3: '&7message3'
compass_item_message_4: '&9message4'
compass_item_message_5: '&2message5'
compass_item_message_6: '&6message6'
compass_item_message_7: '&5message7'
compass_item_message_8: '&bmessage8'
compass_item_message_9: '&amessage9'
##########################################################
#Item Types:
#A list of all VALID items: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html 
#Caps do not matter. If you enter an invalid material, it will go to the default; ENDER_PEARL.
compass_item: 'COMPASS'
compass_item_1: 'ENDER_PEARL'
compass_item_2: 'ENDER_PEARL'
compass_item_3: 'ENDER_PEARL'
compass_item_4: 'ENDER_PEARL'
compass_item_5: 'ENDER_PEARL'
compass_item_6: 'ENDER_PEARL'
compass_item_7: 'ENDER_PEARL'
compass_item_8: 'ENDER_PEARL'
compass_item_9: 'ENDER_PEARL'
toggle_players_item_on: 'REDSTONE_TORCH_ON'
toggle_players_item_off: 'REDSTONE_TORCH_OFF'
########################################################
#Other:
#The torch delay is in seconds.
torch_delay: 5
#This is a list. This needs SPACES. Not tabs
Enabled_Worlds:
  - 'world'